AzureIoTHubConfig:
    DeviceKey: 54e/XSmVRPL1HhkzTfgXWBkYziBc+NB9vNyjGt0emgw=
    IoTHubUri: iot-product-demos.azure-devices.net
    DeviceId: DeviceId
    IotHubD2cEndpoint: messages/events
    ConnectionString: HostName=iot-product-demos.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=zNXayg/LzzcktbIMvNupCOx7KxTdK6tYdwJBno9pLEs=